# SPDX-FIleCopyrightText: Tiara Hock and the Nazara Team <tiara.dev@proton.me>
# SPDX-License-Identifier: LGPL-3.0-only
---
name: Epic
description: Large features containing a collection of issues or tasks. (maintainers only)
title: "[EPIC]"
labels: ["EPIC", "pending"]
body:
    - type: markdown
      attributes:
        value: >
            **NOTE** This form is for maintainers only.
            If you have any questions or are looking for assistance,
            please refer to our [discussion section](https://github.com/orgs/The-Nazara-Project/discussions).

            Also, if you have an issue to report, please report it using the Bug Report template.
    - type: input
      attributes:
          label: Nazara Version
          description: >
              Which upcoming Version of Nazara does this epic target?
          placeholder: master
      validations:
        required: false
    - type: input
      attributes:
        label: NetBox Version
        description: >
            Which version of NetBox is this targeting?
        placeholder: v4.0.0
    - type: textarea
      attributes:
        label: Epic Description
        description: >
            Please describe in detail, what this epic is supposed to do.
      validations:
        required: true
    - type: textarea
      attributes:
        label: Tasks
        description: Please link any sub-issues or tasks here.
