# Template nazara-config.toml file for v0.1.0

# Configuration parameters for the NetBox connection
[netbox]
netbox_api_token = "{NETBOX_TOKEN}"
netbox_uri = "{NETBOX_URI}"

# Mandatory information about the system
[system]
name = "{SYSTEM_NAME}" # Name of the machine or VM. **Required** when device is a VM
site_id = 0 # The id of the site this device is located at. (Stored in NetBox)
# site_name = "" # Name of the site this device is located at. (May take longer to search for) (Mutually exclusive with ID!)
description = ""
comments = "Automatically registered by Nazara."
device_type = 0 # ID of the type of the Device Type in NetBox
device_role = 0 # ID of the device role in NetBox
# Name of the network interface to set. (e.g eth0, etc)
# If not set, the first active interface will be selected.
primary_network_interface = "eth0"
face = "" # Direction this device may face in (e.g front or rear)
status = "active" # status of the device. default: active
airflow = "front-to-rear" # Direction of airflow

# Optional data of your device.
# This section may be empty
[[system.optional]]
# tenant_group = 0 # ID of the department this device belongs to
# tenant_group_name = "" # Name of the department this device belongs to (mutually exclusive with ID!)
# tenant = 0 # ID of the team or individual this device belongs to
# tenant_name = "" # Name of the individual or team this device belongs to (mutually exclusive with ID!)
# location = 0 # ID of the location of the device
# rack = 0 # ID of the rack the device is mounted in if any
# position = 0 # Position of the device within the rack if any
platform = "x86_64"

# Custom parameters about the system, which fall under the "custom_fields" section.
# Basically anything can go here, these are example values Nazara collects.
[system.custom_fields]
# cpu_count = 1 # overriden by collector
# config_template = 0
##  ...
# TODO: Does this make sense if this information is collected anyway?
# TODO: Maybe something like this would be better?
# collect_cpu_information = true
#
# collect_network_information = true

[nwi]
# name = "" # The name of your interface. Must correspond to an interface name present on this device.
# id = 0 # The ID of the desired interface, if it already exists. (Mutually exclusive with name)
# vdcs = []
# module = 0
# label = "" # The physical label on the interface or device, if applicable.
# r#type = "" # The type of the interface (e.g "bridge")
enabled = true # Whether this interface is enabled or not. Default: True.
# parent = 0 # ID of the parent interface if applicable.
# bridge = 0 # ID of the bridge device associated with this interface if applicable.
# lag = 0
# mtu = 0 # 32-bit unsigned interger!
# duplex = ""
# wwn = ""
mgmt_only = false # Whether this interface shall be used for management only. (Default: False)
# description = "" # Optional description of this interface.
# mode = "" # Mode this interface operates in.
# rf_role = ""
# rf_channel = ""
# poe_mode = ""
# poe_type = ""
# rf_channel_frequency = 0.0 # f64 value.
# rf_channel_width = 0.0 # f64 value.
# tx_power = 0 # u8 value
# untagged_vlans = [] # List of IDs of the untagged VLANs associated to this interface.
# tagged_vlans = [] # List of IDs of the tagged VLANs associated to this interfacce.
mark_connected = true # Whether this interface is currently connected or not.
# wireless_lans = [] # List of IDs of the wireless lans associated with this interface.
# vrf = 0

[nwi.custom_fields]
# Custom fields of the interface go here.


